### ISSUE TITLE
aws_route53_record variable not detected

### ISSUE THREAD

**Issue by Sinnohd** [juliosueiras/terraform-lsp#15]
```
01 resource "aws_route53_zone" "domain1-de-public" {
02   name    = "domain1.de"
03   comment = "Test domain"
04 }
05 
06 resource "aws_route53_record" "domain1-de-A" {
07   zone_id = aws_route53_zone.domain1-de-public.zone_id
08   name    = "domain1.de"
09   type    = "A"
10   records = ["192.168.1.1"]
11   ttl     = "3600"
12 }
```

Leads to an error: 
There is no variable named "aws_route53_zone". Terraform Schema [ 7, 13]

Versions:

terraform-lsp 0.5
Terraform v0.12.5
provider.aws v2.21.1
mauve.terraform-1.4.50

**Comment by jharley** [comment]
I am seeing similar behaviour for "aws_iam_policy" and "aws_kms_key" resources, so I think the issue is not specifically the "aws_route53_record" resource

**Comment by juliosueiras** [comment]
Hi, can you try with 0.0.6?

**Comment by Sinnohd** [comment]
Works now. 

Thank you ;)
