### ISSUE TITLE
Unable to download plugin from vscode

### ISSUE THREAD

**Issue by da3mon-01** [juliosueiras/terraform-lsp#19]
Hi!

When trying to install the plugin from mauve-vscode, however I get the following error:

```
Failed to download common providers: Error: ETXTBSY: text file is busy, copyfile '/home/gschaffer/.vscode/extensions/mauve.terraform-1.4.0/lspbin/.terraform/plugins/linux_amd64/terraform-provider-aws_v2.25.0_x4' -> '/home/gschaffer/.vscode/extensions/mauve.terraform-1.4.0/lspbin/terraform-provider-aws_v2.25.0_x4'
```

Any ideas how to solve this?

**Comment by da3mon-01** [comment]
I think this might be related that I also have the mongo atlas provider installed, and using its resources.
Would it be better if the language server also checks stuff under ~/.terraform for providers that might be also installed and not in the list?

**Comment by juliosueiras** [comment]
I think that is on vscode side, since [installation of common provider not in the lsp](https://github.com/lawrencegripper/vscode-terraform/blob/lg/langserver/src/languageclient.ts)

**Comment by gschaffer-cxn** [comment]
You are right, I think the issue was VSCode was trying to run multiple versions the lsp.
Please close this issue.

**Comment by da3mon-01** [comment]
You are right, closing this issue.
