### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by pplatek** [juliosueiras/terraform-lsp#2]
Just cloned this repo and run make:
% make                                
go build && cp ./terraform-lsp ~/.bin/ && cp ./terraform-lsp ~/
# github.com/juliosueiras/terraform-lsp/helper
../juliosueiras/terraform-lsp/helper/file.go:41:3: cannot use diags (type "github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl2/hcl".Diagnostics) as type "github.com/hashicorp/hcl2/hcl".Diagnostics in return argument
../juliosueiras/terraform-lsp/helper/file.go:41:53: impossible type assertion:
	*hclsyntax.Body does not implement "github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl2/hcl".Body (wrong type for Content method)
		have Content(*"github.com/hashicorp/hcl2/hcl".BodySchema) (*"github.com/hashicorp/hcl2/hcl".BodyContent, "github.com/hashicorp/hcl2/hcl".Diagnostics)
		want Content(*"github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl2/hcl".BodySchema) (*"github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl2/hcl".BodyContent, "github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl2/hcl".Diagnostics)
../juliosueiras/terraform-lsp/helper/file.go:57:3: cannot use diags (type "github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl2/hcl".Diagnostics) as type "github.com/hashicorp/hcl2/hcl".Diagnostics in return argument
../juliosueiras/terraform-lsp/helper/file.go:57:49: impossible type assertion:
	*hclsyntax.Body does not implement "github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl2/hcl".Body (wrong type for Content method)
		have Content(*"github.com/hashicorp/hcl2/hcl".BodySchema) (*"github.com/hashicorp/hcl2/hcl".BodyContent, "github.com/hashicorp/hcl2/hcl".Diagnostics)
		want Content(*"github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl2/hcl".BodySchema) (*"github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl2/hcl".BodyContent, "github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl2/hcl".Diagnostics)
../juliosueiras/terraform-lsp/helper/file.go:62:2: cannot use diags (type "github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl2/hcl".Diagnostics) as type "github.com/hashicorp/hcl2/hcl".Diagnostics in return argument
../juliosueiras/terraform-lsp/helper/file.go:62:48: impossible type assertion:
	*hclsyntax.Body does not implement "github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl2/hcl".Body (wrong type for Content method)
		have Content(*"github.com/hashicorp/hcl2/hcl".BodySchema) (*"github.com/hashicorp/hcl2/hcl".BodyContent, "github.com/hashicorp/hcl2/hcl".Diagnostics)
		want Content(*"github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl2/hcl".BodySchema) (*"github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl2/hcl".BodyContent, "github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl2/hcl".Diagnostics)
../juliosueiras/terraform-lsp/helper/file.go:107:35: cannot use &currVar.Type (type *"github.com/hashicorp/terraform/vendor/github.com/zclconf/go-cty/cty".Type) as type *"github.com/zclconf/go-cty/cty".Type in argument to parseVariables
make: *** [Makefile:2: default] Error 2

**Comment by juliosueiras** [comment]
Hi, sorry for the late reply, I updated the README with more build instruction, can you try it again with the step on README?

**Comment by kadrach** [comment]
The README is missing a `mod` in the `GO111MODULE=on go *mod* download` command, but this aside, it works fine using the instructions provided.

**Comment by juliosueiras** [comment]
no problem, fixed the readme, thanks

**Comment by sandangel** [comment]
hi @juliosueiras I have this error when trying to build from source:

```sh
→ go build
# github.com/juliosueiras/terraform-lsp/helper
helper/file.go:42:3: cannot use diags (type "github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl2/hcl".Diagnostics) as type "github.com/hashicorp/hcl2/hcl".Diagnostics in return argument
helper/file.go:42:53: impossible type assertion:
        *hclsyntax.Body does not implement "github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl2/hcl".Body (wrong type for Content method)
                have Content(*"github.com/hashicorp/hcl2/hcl".BodySchema) (*"github.com/hashicorp/hcl2/hcl".BodyContent, "github.com/hashicorp/hcl2/hcl".Diagnostics)
                want Content(*"github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl2/hcl".BodySchema) (*"github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl2/hcl".BodyContent, "github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl2/hcl".Diagnostics)
helper/file.go:57:3: cannot use diags (type "github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl2/hcl".Diagnostics) as type "github.com/hashicorp/hcl2/hcl".Diagnostics in return argument
helper/file.go:57:49: impossible type assertion:
        *hclsyntax.Body does not implement "github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl2/hcl".Body (wrong type for Content method)
                have Content(*"github.com/hashicorp/hcl2/hcl".BodySchema) (*"github.com/hashicorp/hcl2/hcl".BodyContent, "github.com/hashicorp/hcl2/hcl".Diagnostics)
                want Content(*"github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl2/hcl".BodySchema) (*"github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl2/hcl".BodyContent, "github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl2/hcl".Diagnostics)
helper/file.go:62:2: cannot use diags (type "github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl2/hcl".Diagnostics) as type "github.com/hashicorp/hcl2/hcl".Diagnostics in return argument
helper/file.go:62:48: impossible type assertion:
        *hclsyntax.Body does not implement "github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl2/hcl".Body (wrong type for Content method)
                have Content(*"github.com/hashicorp/hcl2/hcl".BodySchema) (*"github.com/hashicorp/hcl2/hcl".BodyContent, "github.com/hashicorp/hcl2/hcl".Diagnostics)
                want Content(*"github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl2/hcl".BodySchema) (*"github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl2/hcl".BodyContent, "github.com/hashicorp/terraform/vendor/github.com/hashicorp/hcl2/hcl".Diagnostics)
helper/file.go:104:35: cannot use &currVar.Type (type *"github.com/hashicorp/terraform/vendor/github.com/zclconf/go-cty/cty".Type) as type *"github.com/zclconf/go-cty/cty".Type in argument to parseVariables

```

**Comment by sandangel** [comment]
oh sorry, that was because I cloned the repo to $GOPATH

**Comment by chucknelson** [comment]
@juliosueiras - Looks like this issue can be closed, right?
