### ISSUE TITLE
There is no variable named "path". Did you mean "data"?

### ISSUE THREAD

**Issue by Itiho** [juliosueiras/terraform-lsp#20]
In code 
`data "template_file" "financeiro_service_params" {
  template = "${file("${path.module}/files/ServiceParams.xml")}"
  vars = {
    core_transacional                     = replace("corf-${var.app_version}", ".", "-")
    authorizer                            = replace("autf-${var.app_version}", ".", "-")
    cielo_switch                          = replace("swit-${var.app_version}", ".", "-")
    bin_switch                            = replace("swit-${var.app_version}", ".", "-")
    fdcorban_switch                       = replace("swit-${var.app_version}", ".", "-")
    libercard_switch                      = replace("swit-${var.app_version}", ".", "-")
    elavon_switch                         = replace("swit-${var.app_version}", ".", "-")
  }
}`

I get this error

> There is no variable named "path". Did you mean "data"?

**Comment by juliosueiras** [comment]
this issue is resolved in the latest version
