### ISSUE TITLE
VSCode preserveFocus

### ISSUE THREAD

**Issue by benmontour-wf** [juliosueiras/terraform-lsp#21]
Currently with terraform-lsp installed alongside the [Terraform Extension for VSCode](https://github.com/mauve/vscode-terraform) this plugin forces the Output window to steal window focus on occasion. There is another issue for VSCode where they state that extension authors need to add preserveFocus: true. This prevents a workflow disruption to the user by not forcing their editor to switch to the Output view. Issue comment linked below.
https://github.com/Microsoft/vscode/issues/31474#issuecomment-319032829

**Comment by juliosueiras** [comment]
emmm......... I checked the lsp specs, and the attached comment, and I think this needed to be added to the vscode-terraform itself, since there is two side , client and server, and terraform-lsp is the server, where as vscode-terraform is the client

**Comment by benmontour-wf** [comment]
Sorry for the mistake. I'll open an issue with that project. Just saw the lsp debug data in Output when it happened.
