### ISSUE TITLE
Add -version flag

### ISSUE THREAD

**Issue by moritzheiber** [juliosueiras/terraform-lsp#24]
It would be really convenient to have the plugin report its current version and maybe commit hash when called with `-version` (or `--version`) as e.g. Terraform does it already:

```sh
$ terraform -version
Terraform v0.12.6
```
This will make it possible to update and install terraform-lsp seamlessly.

**Comment by juliosueiras** [comment]
<img width="1275" alt="Screen Shot 2019-09-18 at 9 54 40 PM" src="https://user-images.githubusercontent.com/3680302/65207274-1fb1b900-da5f-11e9-88a5-0b71edfa2eea.png">

This ok?

**Comment by moritzheiber** [comment]
Brilliant, thanks!
