### ISSUE TITLE
Github provider support / ignore unsupported providers

### ISSUE THREAD

**Issue by chriswacker** [juliosueiras/terraform-lsp#30]
I would really like to see Github provider support. Or at least, an option to ignore unsupported providers so errors are not thrown in VS Code (maybe that is an issue for the extension repo?)

Thank you!

**Comment by chriswacker** [comment]
I discovered a workaround: Adding the provider to $HOME\.vscode\extensions\mauve.terraform-1.4.0\lspbin\providers.tf and then reloading VS Code will get rid of the errors. Again, sorry if this is more appropriate for https://github.com/mauve/vscode-terraform, I am not sure.

**Comment by juliosueiras** [comment]
yeah, since the plugin support any 0.12+ provider , as long as it can access the binary, so this is a more vscode-terraform thing
