### ISSUE TITLE
Support resolving resources in neighboring files

### ISSUE THREAD

**Issue by tomasaschan** [juliosueiras/terraform-lsp#33]
If I have two terraform files next to each-other, resources in one are not found when the language server inspects the other, even though they work perfectly fine when placed in the same file.

Example:
```hcl
# in main.tf
resource "aws_lambda_function" "function" {
  function_name = "foo"
  role        = aws_iam_role.foo.arn # squigglies under aws_iam_role here
  # more props
}

# in iam.tf
resource "aws_iam_role" "foo" {
   # props
}
```
The above config gives an error on the indicated line, saying "There's no variable named aws_iam_role". If I move the two resources to the same file, though, it does not report an error.

**Comment by lfdominguez** [comment]
Same behavior on submodules
