### ISSUE TITLE
Support vim-lsp

### ISSUE THREAD

**Issue by tmpm697** [juliosueiras/terraform-lsp#4]
Can you support build via: `go get -u github.com/juliosueiras/terraform-lsp` ?

and can this plugin supports run through `vim-lsp` for easier integrated with vim? `https://github.com/prabirshrestha/vim-lsp`

**Comment by tmpm697** [comment]
This plugin works with `vim-lsp`

**Comment by kadrach** [comment]
```viml
if executable('terraform-lsp')
    au User lsp_setup call lsp#register_server({
        \ 'name': 'tf',
        \ 'cmd': {server_info->['terraform-lsp']},
        \ 'whitelist': ['tf'],
        \ })
endif
```

I had to disable `hashivim/vim-terraform` to get the language server working, haven't looked into what's conflicting there. Most likely something on my end.

**Comment by tmpm697** [comment]
I had the same, `vim-terraform` conflicts with `terraform-lsp`, had to disable `vim-terraform`
