### ISSUE TITLE
Http 403 : Install/Update update Language Server

### ISSUE THREAD

**Issue by jmyers82** [juliosueiras/terraform-lsp#40]
When trying to install the 0.09 language server I get an unexpected http 403 error.  Is there a way to turn on debugging to possibly capture more detailed logs.  I am behind a proxy and proxy is set as required but wondering if this extension bypasses proxy settings? 

Downloading Terraform language server failed with Error: Unexpected HTTP response: 403

**Comment by juliosueirasED** [comment]
Question.... is this about the lsp itself or vscode-terraform?

**Comment by juliosueiras** [comment]
Question.... is this about the lsp itself or vscode-terraform?

**Comment by jmyers82** [comment]
well it is lsp I believe.  When I press F1 and chose the `Terraform: Install/Upgrade Language Server` is when I get the error.

**Comment by juliosueiras** [comment]
will close this for now, please reopen if the issue still persist in the newest version
