### ISSUE TITLE
Support to specify plugins directory through the command line

### ISSUE THREAD

**Issue by urbas** [juliosueiras/terraform-lsp#49]
This is useful if you have pre-downloaded plugins in your custom plugins directory.

I'm trying to use the terraform language server with visual studio code and the only way I can customize it is through command line arguments.

Currently the terraform language server doesn't work for me because it doesn't find the plugins in my custom folder.

**Comment by dohq** [comment]
I created https://github.com/juliosueiras/terraform-lsp/pull/52

**Comment by juliosueiras** [comment]
the check for .terraform directory is implemented in the latest version
