### ISSUE TITLE
Correct command to run lsp

### ISSUE THREAD

**Issue by tmpm697** [juliosueiras/terraform-lsp#5]
I run through lsp: `\ 'cmd': {server_info->['terraform-lsp']},` is this correct cmmand to run?

I can't make it run as in demo, no completion menu when I trigger autocomplete inside resource's { as in demo.

**Comment by juliosueiras** [comment]
do you still have issue with running it?

**Comment by tmpm697** [comment]
I still have issue that this plugin can't work with `vim-terrafrom`.
