### ISSUE TITLE
Add support for dense-analysis/ale Vim plugin

### ISSUE THREAD

**Issue by andrewimeson** [juliosueiras/terraform-lsp#57]
It'd be great to have support added to work with the [ALE linter](https://github.com/dense-analysis/ale) in Vim.

There are already a few [Terraform related linters that are automatically enabled in ALE.](https://github.com/dense-analysis/ale/tree/master/ale_linters/terraform)

ALE supports command completion using LSP.

**Comment by AubreySLavigne** [comment]
This would be handled on the ALE side.

Issue is here: https://github.com/dense-analysis/ale/pull/2758

Looks like the initial PR was created, w0rp requested tests, then ... no reply after that.

**Comment by AubreySLavigne** [comment]
The tests have been added, so the PR is waiting for review from w0rp. Hopefully it will be added soon. 

If you would like to use this linter with ALE, you can use my fork/branch directly: https://github.com/AubreySLavigne/ale/tree/terraform-lsp
