### ISSUE TITLE
100% CPU util on 0.0.10 on MacOS

### ISSUE THREAD

**Issue by alfiewhelan** [juliosueiras/terraform-lsp#58]
OS: MacOS 10.15.3
VS Code: 1.42.1
Go: 1.13.8 darwin/amd64

After running the Install/Update Language Server command to upgrade to 0.0.10, the terraform-lsp process goes nuts and maxes out the CPU until it is killed. I tried leaving it a while to see if it would settle down but the process consumes all CPU time until it is killed, making the machine unusable until then.

![image](https://user-images.githubusercontent.com/46001232/74655678-a987be80-5184-11ea-971e-805019675b6c.png)

My configuration:

    "terraform.indexing": {
        "enabled": false,
        "liveIndexing": false,
        "delay": 500,
        "exclude": [
            ".terraform/**/*",
            "**/.terraform/**/*"
        ]
    },
    "terraform.languageServer": {
        "enabled": true,
        "args": []
    },
    "terraform.codelens.enabled": true,
    "terraform.format": {
        "ignoreExtensionsOnSave": [
          ".tfsmurf"
        ]
      },
      "terraform.path": "terraform"

To fix the problem I disabled the language server and used the Install/Update command to downgrade to 0.0.9.

A colleague updated his language server and got the same issue.

**Comment by juliosueirasED** [comment]
Can you show a example of the code or project structure?

**Comment by juliosueiras** [comment]
Can you show a example of the code or project structure?

**Comment by alfiewhelan** [comment]
It's a large, complex repo on AWS with many (~60) modules and numerous accounts. There are central accounts that use their own terraform configuration files, as well as some of the modules, and there are non-central accounts that only contain a .tfvars file which populates a "template" which is a module of modules.

Something like:
├── modules
│   ├── 1
│   ├── 2
│   ├── ...
├── org
│   ├── template
│   │   ├── main.tf,
│   │   ├── modules.tf
│   │   ├── backend.tf
│   │   ├── variables.tf
│   ├── account-type-a
│   │   ├── account-a-1
│   │   │   ├── dev
│   │   │   │   └── terraform.tfvars
│   │   │   ├── prod
│   │   │   │   └── terraform.tfvars
│   │   │   ├── test
│   │   │   │   └── terraform.tfvars
│   ├── central
│   │   ├── central-1
│   │   │   ├── resource-1.tf
│   │   │   ├── resource-2.tf
│   │   │   ├── backend.tf.
│   │   │   ├── modules.tf
│   │   │   ├── variables.tf

There are ~700 terraform files and over 100,000 lines of code (not all of which is terraform, but a lot of it).

**Comment by juliosueiras** [comment]
ah found the issue XD, sorry about this

**Comment by juliosueiras** [comment]
to explain , I will be restricting the search for .terraform to 4 level deep, because the way os treat root level path, the lsp goes into recursive loop

**Comment by alfiewhelan** [comment]
> to explain , I will be restricting the search for .terraform to 4 level deep, because the way os treat root level path, the lsp goes into recursive loop

Nice! Thanks for the quick turnaround

**Comment by juliosueiras** [comment]
@alfiewhelan k, can you reinstall v0.0.10? and the issue should not persist anymore

**Comment by alfiewhelan** [comment]
CPU is normal and the auto-completion seems to work!

![image](https://user-images.githubusercontent.com/46001232/74665130-f5dbfa00-5196-11ea-9186-661c38d15db0.png)

Thanks

**Comment by arestarh** [comment]
> 100% ? lol, lucky ...
> <img alt="1079 8" width="837" src="https://user-images.githubusercontent.com/5287237/74903810-872fb400-53c3-11ea-94ab-5d5cedec65c2.png">
> it has drained my battery while I was connected to power!
> mbp 16" i9 + macos catalina 10.15.3 + vscode + lsp 0.10
> how to reinstall it ?
> can't find instructions

Hi,

At least in Visual Studio Code you can press **Ctrl+Shift+P** and choose **Terraform: Install\Update Language Server**:
![image](https://user-images.githubusercontent.com/1265974/74912342-3457fb80-53c7-11ea-9546-2870ca2d3444.png)

**Comment by johngeorgewright** [comment]
> 100% ? lol, lucky ...
> <img alt="1079 8" width="837" src="https://user-images.githubusercontent.com/5287237/74903810-872fb400-53c3-11ea-94ab-5d5cedec65c2.png">
> it has drained my battery while I was connected to power!
> mbp 16" i9 + macos catalina 10.15.3 + vscode + lsp 0.10
> how to reinstall it ?
> can't find instructions

I had this exact same problem. For me I needed to uninstall/install the extension. Using the "Terraform: Install/Update Language Server" option did not do anything for me.

**Comment by qtheya** [comment]
Linux Mint 18.x
![image](https://user-images.githubusercontent.com/9653011/76958007-8be27c00-691f-11ea-82e0-cd49bda26414.png)

**Comment by juliosueiras** [comment]
@qtheya is it possible describe the steps that you took to cause the memory spike?

**Comment by qtheya** [comment]
Hi. Sure.
mkdir module_name
cd module_name
touch {variables.tf,main.tf,outputs.tf}
code .
started writing tf code ..
.. spike ..
My vscode version = 1.43.1
mauve.terraform version = 1.4.0
tf version = 0.12.23
tflint version = 0.15.2
vscode tf settings :
```
    "terraform.path": "/usr/local/bin/terraform",
    "terraform.lintPath": "/usr/local/bin/tflint",
    "terraform.indexing": {
        "enabled": false,
        "liveIndexing": false,
        "delay": 500,
        "exclude": [
            ".terraform/**/*",
            "**/.terraform/**/*"
        ]
    },
    "terraform.format": {
        "enable": true,
        "ignoreExtensionsOnSave": [
            ".tfsmurf",
            ".tfvars"
        ],
        "formatOnSave": true
    },
    "[terraform]": {
        "editor.formatOnSave": true
    },
    "terraform.languageServer": {
        "enabled": true,
        "args": []
    },
```

**Comment by juliosueiras** [comment]
@qtheya what is the terraform-lsp version that was being used?

**Comment by qtheya** [comment]
terraform-lsp --version
v0.0.10, commit: cb1f3966b7c83c497ac2494e621d30f290ae1356

**Comment by juliosueiras** [comment]
will close this for now, please reopen if the issue still persist in the newest version
