### ISSUE TITLE
Segfault when loading plugins, crashes when editing files

### ISSUE THREAD

**Issue by amasover** [juliosueiras/terraform-lsp#67]
I'm not sure if these two crashes are related, but wanted to report them here. Possibly related: #22 #6 #47 

Crash while loading plugins:
https://gist.github.com/amasover/196510ec7e26e8c1dfd0934ac4f7e67d

Crash while editing files:
https://gist.github.com/amasover/ac5c54168fabc5152f4712664e0ac608

Using emacs lsp-mode (20200319.1251) with terraform-lsp v0.0.10.

**Comment by amasover** [comment]
I built the latest master and turned on jrpc debugging. Looks like it's crashing on `textDocument/completion`:

```
Processing 1 requests
Checking request for "textDocument/completion": {"textDocument":{"uri":"file:///home/aaron/code/intro-to-terraform/database/main.tf"},"position":{"line":32,"character":28},"context":{"triggerKind":2,"triggerCharacter":"."}}
Received 1 new requests
Received 1 new requests
Processing 1 requests
Checking request for "textDocument/documentLink": {"textDocument":{"uri":"file:///home/aaron/code/intro-to-terraform/database/main.tf"}}
Processing 1 requests
Checking request for "textDocument/documentLink": {"textDocument":{"uri":"file:///home/aaron/code/intro-to-terraform/database/main.tf"}}
Completed 1 requests [108.193µs elapsed]
Completed 1 requests [164.224µs elapsed]
```
I wonder if the crash just happens whenever no plugins load successfully. I still can't figure out why I can't seem to get any plugins to load.

Here is a crash log for the version built from master:
https://gist.github.com/amasover/57e0526790184f4ed4270d316dfedc99

Looks like it's crashing on langserver/complete.go:56:
```go
	files, diags := configs.NewModule(resultFiles, nil)
```

**Comment by juliosueiras** [comment]
will close this for now, please reopen if the issue still persist in the newest version

**Comment by amasover** [comment]
Still seeing this behavior in the latest version.
