### ISSUE TITLE
IDENT on file()

### ISSUE THREAD

**Issue by nickelghost** [juliosueiras/terraform-lsp#68]
Hello, I'm using the latest version of this language server (version 10) with the vscode extension. I'm getting the IDENT error on the file() function like so:
<img width="374" alt="Screenshot 2020-03-28 at 00 13 43" src="https://user-images.githubusercontent.com/16365643/77807731-fe262f80-7088-11ea-9274-faf03c89800e.png">
Running `terraform plan` or `terraform apply` works fine.
Thanks for the great work!

**Comment by juliosueiras** [comment]
closing this, since this issue happen when the lsp is not enabled on vscode-terraform
