### ISSUE TITLE
request failed, reason: certificate has expired

### ISSUE THREAD

**Issue by fpena06** [juliosueiras/terraform-lsp#70]
Hello,

Using mauve.terraform when running install/update language server I get the following error.

`request to https://api.github.com/repos/juliosueiras/terraform-lsp/releases failed, reason: certificate has expired`

OS: osx catalina 10.15.2
vscode version: 1.43.2

**Comment by juliosueiras** [comment]
Check again later or your local network config since that is not related to this plugin or vscode-terraform but instead has to do with github API

**Comment by fpena06** [comment]
Thanks. I will give it another try and let you know.

**Comment by fpena06** [comment]
Issue was related to [https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github](url)
