### ISSUE TITLE
Flag to change the location of tf-lsp.log

### ISSUE THREAD

**Issue by bigjazzsound** [juliosueiras/terraform-lsp#9]
I would love to have the option to change the location of the tf-lsp.log file, or maybe an option to disable it altogether. I'm currently using this with coc-nvim and it works great, I just have to keep deleting those pesky log files. Thanks!

**Comment by juliosueiras** [comment]
Hi, I added two flags

`-enable-log-file` : to enable log to file

`-log-location <path>/` : location to put the log in

**Comment by bigjazzsound** [comment]
Just tried out the new version and the log files are no longer present by default. Thanks.
