### ISSUE TITLE
Plans to support terraform 0.15

### ISSUE THREAD

**Issue by MAliNaqvi** [juliosueiras/terraform-lsp#94]
Hi Julio,
Thank you for the amazing project.

Was wondering, if there are any plans to support the latest version of terraform?

**Comment by juliosueirasED** [comment]
Yes, will be pushing an update to fix the issue on 0.15

**Comment by MAliNaqvi** [comment]
Awesome! Thank you!

**Comment by MAliNaqvi** [comment]
Noticed that by modifying the `terraform.required_providers` block in the beginning and initializing with terraform 12, allows most of the autocomplete to continue as normal. 

So, majority of the change could be handled by being able to traverse through `.terraform` folder created during init in `0.15` vs in `0.12`.

**Comment by juliosueiras** [comment]
can you try 0.0.12 ?

**Comment by MAliNaqvi** [comment]
Amazing work!

<img width="339" alt="image" src="https://user-images.githubusercontent.com/13531332/118413878-7d047000-b66f-11eb-9af8-28c04d1a48f9.png">
<img width="296" alt="image" src="https://user-images.githubusercontent.com/13531332/118413893-93123080-b66f-11eb-80f5-7080d686bb9b.png">

Thank you!
